---
sudo: false
dist: bionic
language: ruby
rvm:
  - 2.5.5
matrix:
  include:
    - env: OPENSTUDIO_VERSION=3.0.1 OPENSTUDIO_SHA=09b7c8a554 RUBYLIB=/usr/local/openstudio-3.0.1/Ruby:/usr/Ruby
before_install:
  - gem install bundler
  - bundle -v
install:
  - bundle install
before_script:
  - curl -LO https://github.com/NREL/OpenStudio/releases/download/v3.0.1/OpenStudio-3.0.1+09b7c8a554-Linux.deb
  - sudo apt install ./OpenStudio-3.0.1+09b7c8a554-Linux.deb
script:
  # run all tests together
  - bundle exec rspec